export const DECISION_STATUS = Object.freeze({
  READY: 'READY',
  WATCH: 'WATCH',
  WAIT: 'WAIT',
  REJECTED: 'REJECTED',
})

export const PIPELINE_STAGE = Object.freeze({
  OPEN_DAY: 'OPEN_DAY',
  FIXTURE_DISCOVERY: 'FIXTURE_DISCOVERY',
  BASE_ENRICHMENT: 'BASE_ENRICHMENT',
  PRE_RANKING: 'PRE_RANKING',
  CANDIDATE_POOL_READY: 'CANDIDATE_POOL_READY',
  MARKET_AVAILABILITY_SCAN: 'MARKET_AVAILABILITY_SCAN',
  MARKET_RECONCILIATION: 'MARKET_RECONCILIATION',
  DEEP_ANALYSIS: 'DEEP_ANALYSIS',
  DECISION_CLASSIFICATION: 'DECISION_CLASSIFICATION',
  DECISION_BOARD_READY: 'DECISION_BOARD_READY',
  RESULT_REFRESH: 'RESULT_REFRESH',
  RESULT_SETTLEMENT: 'RESULT_SETTLEMENT',
  COMPLETE: 'COMPLETE',
})

export const REQUIRED_PIPELINE_SEQUENCE = Object.freeze([
  PIPELINE_STAGE.OPEN_DAY,
  PIPELINE_STAGE.FIXTURE_DISCOVERY,
  PIPELINE_STAGE.BASE_ENRICHMENT,
  PIPELINE_STAGE.PRE_RANKING,
  PIPELINE_STAGE.CANDIDATE_POOL_READY,
  PIPELINE_STAGE.MARKET_AVAILABILITY_SCAN,
  PIPELINE_STAGE.MARKET_RECONCILIATION,
  PIPELINE_STAGE.DEEP_ANALYSIS,
  PIPELINE_STAGE.DECISION_CLASSIFICATION,
  PIPELINE_STAGE.DECISION_BOARD_READY,
  PIPELINE_STAGE.RESULT_REFRESH,
  PIPELINE_STAGE.RESULT_SETTLEMENT,
  PIPELINE_STAGE.COMPLETE,
])

export const FUTURE_PIPELINE_STAGE = Object.freeze({
  NEAR_KICKOFF_REFRESH: 'NEAR_KICKOFF_REFRESH',
  FINAL_LOCK: 'FINAL_LOCK',
})

export const MARKET_TYPE = Object.freeze({
  ASIAN_HANDICAP: 'ASIAN_HANDICAP',
  OVER_UNDER: 'OVER_UNDER',
  MATCH_WINNER: 'MATCH_WINNER',
  DOUBLE_CHANCE: 'DOUBLE_CHANCE',
  CORRECT_SCORE: 'CORRECT_SCORE',
  BTTS: 'BTTS',
  UNKNOWN: 'UNKNOWN',
})

export const RISK_LEVEL = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
})

export const REASON_CODE = Object.freeze({
  READY_ALL_GATES_PASSED: 'READY_ALL_GATES_PASSED',
  WAIT_MARKET_MISSING: 'WAIT_MARKET_MISSING',
  WAIT_MARKET_STALE: 'WAIT_MARKET_STALE',
  WAIT_MARKET_REFRESH: 'WAIT_MARKET_REFRESH',
  WAIT_ANALYSIS_INCOMPLETE: 'WAIT_ANALYSIS_INCOMPLETE',
  WATCH_CONFIDENCE_BELOW_READY: 'WATCH_CONFIDENCE_BELOW_READY',
  WATCH_MARKET_EDGE_WEAK: 'WATCH_MARKET_EDGE_WEAK',
  WATCH_DATA_QUALITY_BORDERLINE: 'WATCH_DATA_QUALITY_BORDERLINE',
  REJECT_FIXTURE_INVALID: 'REJECT_FIXTURE_INVALID',
  REJECT_UNSUPPORTED_LEAGUE: 'REJECT_UNSUPPORTED_LEAGUE',
  REJECT_DATA_QUALITY_FAILED: 'REJECT_DATA_QUALITY_FAILED',
  REJECT_ANALYSIS_INVALID: 'REJECT_ANALYSIS_INVALID',
  REJECT_RISK_CRITICAL: 'REJECT_RISK_CRITICAL',
  REJECT_MATCH_NOT_PLAYABLE: 'REJECT_MATCH_NOT_PLAYABLE',
  REJECT_FINAL_PICK_INVALID: 'REJECT_FINAL_PICK_INVALID',
})

export const FIXTURE_ONLY_CONFIDENCE_CAP = 60
