import { deepFreeze } from './immutable.js'

export const DECISION_STATUS = deepFreeze({
  READY: 'READY',
  WATCH: 'WATCH',
  WAIT: 'WAIT',
  REJECTED: 'REJECTED',
})

export const PIPELINE_STAGE = deepFreeze({
  OPEN_DAY: 'OPEN_DAY',
  FIXTURE_DISCOVERY: 'FIXTURE_DISCOVERY',
  BASE_ENRICHMENT: 'BASE_ENRICHMENT',
  PRE_RANKING: 'PRE_RANKING',
  CANDIDATE_POOL_READY: 'CANDIDATE_POOL_READY',
  MARKET_AVAILABILITY_SCAN: 'MARKET_AVAILABILITY_SCAN',
  MARKET_RECONCILIATION: 'MARKET_RECONCILIATION',
  DEEP_ANALYSIS: 'DEEP_ANALYSIS',
  DECISION_CLASSIFICATION: 'DECISION_CLASSIFICATION',
  DECISION_BOARD_READY: 'DECISION_BOARD_READY',
  RESULT_REFRESH: 'RESULT_REFRESH',
  RESULT_SETTLEMENT: 'RESULT_SETTLEMENT',
  COMPLETE: 'COMPLETE',
})

export const REQUIRED_PIPELINE_SEQUENCE = deepFreeze([
  PIPELINE_STAGE.OPEN_DAY,
  PIPELINE_STAGE.FIXTURE_DISCOVERY,
  PIPELINE_STAGE.BASE_ENRICHMENT,
  PIPELINE_STAGE.PRE_RANKING,
  PIPELINE_STAGE.CANDIDATE_POOL_READY,
  PIPELINE_STAGE.MARKET_AVAILABILITY_SCAN,
  PIPELINE_STAGE.MARKET_RECONCILIATION,
  PIPELINE_STAGE.DEEP_ANALYSIS,
  PIPELINE_STAGE.DECISION_CLASSIFICATION,
  PIPELINE_STAGE.DECISION_BOARD_READY,
  PIPELINE_STAGE.RESULT_REFRESH,
  PIPELINE_STAGE.RESULT_SETTLEMENT,
  PIPELINE_STAGE.COMPLETE,
])

export const FUTURE_PIPELINE_STAGE = deepFreeze({
  NEAR_KICKOFF_REFRESH: 'NEAR_KICKOFF_REFRESH',
  FINAL_LOCK: 'FINAL_LOCK',
})

export const MARKET_TYPE = deepFreeze({
  ASIAN_HANDICAP: 'ASIAN_HANDICAP',
  OVER_UNDER: 'OVER_UNDER',
  MATCH_WINNER: 'MATCH_WINNER',
  DOUBLE_CHANCE: 'DOUBLE_CHANCE',
  CORRECT_SCORE: 'CORRECT_SCORE',
  BTTS: 'BTTS',
  UNKNOWN: 'UNKNOWN',
})

export const RISK_LEVEL = deepFreeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
})

export const MATCH_STATUS_CATEGORY = deepFreeze({
  PREMATCH_DECISION_ELIGIBLE: 'PREMATCH_DECISION_ELIGIBLE',
  STARTED_OR_LIVE: 'STARTED_OR_LIVE',
  TERMINAL_OR_VOID: 'TERMINAL_OR_VOID',
  RETRYABLE_NOT_READY: 'RETRYABLE_NOT_READY',
  UNKNOWN: 'UNKNOWN',
})

export const REASON_CODE = deepFreeze({
  READY_ALL_GATES_PASSED: 'READY_ALL_GATES_PASSED',
  WAIT_MARKET_MISSING: 'WAIT_MARKET_MISSING',
  WAIT_MARKET_STALE: 'WAIT_MARKET_STALE',
  WAIT_MARKET_REFRESH: 'WAIT_MARKET_REFRESH',
  WAIT_ANALYSIS_INCOMPLETE: 'WAIT_ANALYSIS_INCOMPLETE',
  WAIT_MATCH_RESCHEDULE: 'WAIT_MATCH_RESCHEDULE',
  WATCH_CONFIDENCE_BELOW_READY: 'WATCH_CONFIDENCE_BELOW_READY',
  WATCH_MARKET_EDGE_WEAK: 'WATCH_MARKET_EDGE_WEAK',
  WATCH_DATA_QUALITY_BORDERLINE: 'WATCH_DATA_QUALITY_BORDERLINE',
  REJECT_FIXTURE_INVALID: 'REJECT_FIXTURE_INVALID',
  REJECT_UNSUPPORTED_LEAGUE: 'REJECT_UNSUPPORTED_LEAGUE',
  REJECT_DATA_QUALITY_FAILED: 'REJECT_DATA_QUALITY_FAILED',
  REJECT_ANALYSIS_INVALID: 'REJECT_ANALYSIS_INVALID',
  REJECT_RISK_CRITICAL: 'REJECT_RISK_CRITICAL',
  REJECT_MATCH_ALREADY_STARTED: 'REJECT_MATCH_ALREADY_STARTED',
  REJECT_MATCH_NOT_PLAYABLE: 'REJECT_MATCH_NOT_PLAYABLE',
  REJECT_FINAL_PICK_INVALID: 'REJECT_FINAL_PICK_INVALID',
  REJECT_THRESHOLD_INVALID: 'REJECT_THRESHOLD_INVALID',
})

// Match-status gates apply only when a Decision is newly created or recomputed.
// They do not delete a Decision that was created and locked before kickoff.

export const FIXTURE_ONLY_CONFIDENCE_CAP = 60

export const DEFAULT_DECISION_THRESHOLDS = deepFreeze({
  readyConfidenceThreshold: 80,
  watchConfidenceThreshold: 70,
  minimumDataQuality: 60,
  marketFreshnessHours: 12,
})

export const CONFIDENCE_COMPONENT_WEIGHTS = deepFreeze({
  dataQuality: 0.25,
  analysisQuality: 0.25,
  modelAgreement: 0.2,
  marketCompleteness: 0.15,
  marketFreshness: 0.15,
})
